[phases.setup]
nixPkgs = ['nginx', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = "php artisan reverb:start --host=0.0.0.0 --port=8080 & php artisan serve --host=0.0.0.0 --port=$PORT"
