on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11  
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: urbanwatch_testing
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - uses: actions/checkout@v4

    # 1. Setup PHP Environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    # 2. Install Backend Dependencies
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install NPM packages
      run: npm ci

    - name: Build Frontend Assets
      run: npm run build

    - name: Check Code Style (Pint)
      run: ./vendor/bin/pint --test
      
    - name: Execute tests (Unit and Feature)
      env:
        # Override the phpunit.xml sqlite defaults
        DB_CONNECTION: mariadb
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: urbanwatch_testing
        DB_USERNAME: root
        DB_PASSWORD: 
      run: php artisan test